export { default as Check } from '@ant-design/icons/lib/outline/CheckOutline'
export { default as Close } from '@ant-design/icons/lib/outline/CloseOutline'
export { default as Calendar } from '@ant-design/icons/lib/outline/CalendarOutline'
export { default as Down } from '@ant-design/icons/lib/outline/DownOutline'
export { default as Up } from '@ant-design/icons/lib/outline/UpOutline'